server:
  port: 8000
spring:
  application:
    name: photo
  datasource:
    dbcp2:
      initial-size: 7
      max-total: 20
      pool-prepared-statements: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect