INSERT INTO USER (ID, LOGIN) VALUES (1, 'user1');

INSERT INTO USER (ID, LOGIN) VALUES (2, 'user2');
INSERT INTO USER (ID, LOGIN) VALUES (3, 'user3');


INSERT INTO PHOTO (ID, PHOTO_URL, USER_ID, LAT, LON) VALUES (1, 'http://', 1, 1, 1);

INSERT INTO PHOTO (ID, PHOTO_URL, USER_ID, LAT, LON) VALUES (2, 'http://', 1, 2, 2);

INSERT INTO PHOTO (ID, PHOTO_URL, USER_ID, LAT, LON) VALUES (3, 'http://', 2, 3, 3);

INSERT INTO PHOTO (ID, PHOTO_URL, USER_ID, LAT, LON) VALUES (4, 'http://', 2, 5, 5);

INSERT INTO PHOTO (ID, PHOTO_URL, USER_ID, LAT, LON) VALUES (5, 'http://', 3, 7, 7);

INSERT INTO PHOTO (ID, PHOTO_URL, USER_ID, LAT, LON) VALUES (7, 'http://', 3, 9, 9);



